### ISSUE TITLE
error when i try to start the server

### ISSUE THREAD

**Issue by ciruela** [marcosolina/csgo_server#2]
![error](https://user-images.githubusercontent.com/62853066/148468511-8b879f14-5956-43e9-b6e7-f88ae530ae62.png)

**Comment by marcosolina** [comment]
Hi @ciruela thank you for you message. Looking at your screenshot seems like that for some reason the steamcmd or csgo was not installed correctly. 

One quick thing that you can try to do is to delete the folder /home/abritos/cosas/csgo and re-install the server again.

Otherwise could you please share additional details like:
- Is this the first time that you are trying to start the server?
- Do you remember seeing the following screen during the installation process?
  ![image](https://user-images.githubusercontent.com/26163844/148513957-e658ac75-314a-47f9-bea6-46c5976e1ebd.png)

**Comment by marcosolina** [comment]
Hi @ciruela did had any chance to try what I suggested or collect the info that I asked you? Plase let me know if you still have problems, otherwise I'll have to close this issue, thanks

**Comment by marcosolina** [comment]
Closing the issue as the additional inforamtion were not provided
